---

- name: First-steps_linux | debian.yml | Update Apt Package Cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: First-steps_linux | debian.yml | Install apt-get Universal Requirements
  ansible.builtin.apt:
    name: "{{ apt_standard_install }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ cache_valid_time_var }}"
  become_user: root
  become: true

- name: First-steps_linux | debian.yml | Sudo apt-get upgrade
  ansible.builtin.apt:
    upgrade: full
  register: upgrade_apt
  become_user: root
  become: true
  retries: 15
  delay: 5
  until: upgrade_apt is success

- name: First-steps_linux | debian.yml | Output of upgrade_apt
  ansible.builtin.debug:
    var: upgrade_apt

- name: First-steps_linux | debian.yml | Sudo apt-get dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
  register: dist_apt
  become_user: root
  become: true
  retries: 15
  delay: 5
  until: dist_apt is success

- name: First-steps_linux | debian.yml | Output of dist_apt
  ansible.builtin.debug:
    var: dist_apt

- name: First-steps_linux | debian.yml | Check if a reboot is needed for Debian-based systems
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: First-steps_linux | debian.yml | Reboot the server if needed
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible because of reboot required file"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists

- name: First-steps_linux | debian.yml | Sudo apt-get autoclean
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  register: autoclean_apt
  become_user: root
  become: true

- name: First-steps_linux | debian.yml | Show output of autoclean_apt
  ansible.builtin.debug:
    var: autoclean_apt
